name: pcoc
description: Permanent Committee for Organizing Conferences

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  auto_size_text: ^3.0.0
  beamer: ^1.5.0
  cross_file: ^0.3.3+1
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  email_validator: ^2.0.1
  expansion_widget: ^0.0.3
  file_picker: ^4.6.1
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_dropzone: ^3.0.5
  flutter_hooks: ^0.18.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.0
  flutter_typeahead: ^4.0.0
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  hovering: ^1.0.4
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  lazy_load_scrollview: ^1.3.0
  mime_type: ^1.0.0
  path: ^1.8.1
  riverpod_request_helpers:
    git:
      url: https://github.com/Fidev-io/riverpod_request_helpers.git
  shared_preferences: ^2.0.15
  states_rebuilder: ^6.1.0+1
  url_launcher: ^6.1.3

dev_dependencies:
  analyzer: ^4.1.0
  build_runner: ^2.1.11
#  flutter_test:
#    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/guests/
    - assets/stadiums/
    - assets/flags/
